# https://www.home-assistant.io/integrations/default_config/
default_config:

http:
  server_port: 1234

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.integration_blueprint: debug
